// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdbnfgignthxgbnpcmfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkYm5mZ2lnbnRoeGdibnBjbWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTM1MjEsImV4cCI6MjA2MzQyOTUyMX0.y3Xgb53IIzsb6-X-PHhVvZfG20saGKTaQMV9xT4Lryg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);